[package]
name = "rustvault"
version = "0.1.0"
edition = "2021" # To this line

[lib]
crate-type = ["cdylib"]  # this tells Rust to compile as a native C library

[dependencies]
aes = "0.8"
ctr = { version = "0.9", features = ["alloc"] }
base64 = "0.21"
sha2 = "0.10"
jni = "0.21"
